spring:
  application:
    name: mdong_prac
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: 326030

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080

springdoc:
  swagger-ui:
    #swagger-ui ?? ?? ?? (???? /swagger-ui.html??)
    path: /swagger-ui.html
    #? api? ?? ?? ??(desc : ????)
    groups-order: desc
    #?? ?? ?? (alpha : ??? ?? ??)
    tags-sorter: alpha
    #controller ?? ?? (method : delete - get - patch - post - put ? ??)
    operations-sorter: method
    #swagger-ui? ??? url? petstore html? ?? ????
    disable-swagger-default-url: true
    #swagger-ui?? try ?, request duration(api ?? ? ?? ??)? ???? ??
    display-request-duration: true
  #openAPI ?? ?? (default ?: /v3/api-docs) -> swagger? api ??? ?? ?? ??? ?????, openAPI? api?? ??? ? ??? ???.
  api-docs:
    path: /api-docs
  #"spring Actuator? endpoint"(-> ???? ? ??? api)?? ??? ???? ?? ??
  show-actuator: true
  #request media type? ?? ?
  default-consumes-media-type: application/json
  #response media type? ?? ?
  default-produces-media-type: application/json
  #?? ?? endpoint? ?? controller? swagger-ui? ????.
  paths-to-match:
    - /api/**
